version: "3"
services:
  mongo:
    image: mongo:4.1.6
    environment:
      - MONGO_DATA_DIR=/data/mongo
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/mongo:/data/mongo

  backend:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - 8080:8080

  mongo-admin:
    image: mrvautin/adminmongo
    environment:
      - HOST=0.0.0.0
      - PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - mongo
