version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0
        environment:
          TEST_ENV: circle
      - image: mongo:4.1.6

    working_directory: ~/overdeer-api

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run unit tests
          command: |
            npm run test:unit
